# Generated by Django 4.0.2 on 2023-06-07 11:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short_description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='products',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Time of Modified'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
